address: mongodb://localhost:27017/
database: DEFAULT_DB
collection: installations
request:
  headers: { 'content-type': 'application/json' }
  params: { 'technicalToken': 'PDcX1hJkKfNPLfuBAses8wq3QiwRQRttkvh9CQjbTUOvY8WmpYFnkTeZZyGDfZWn' }
  powerProductionUrl: http://localhost:8082/api/1/powerProduction
  powerProducedUrl: http://localhost:8082/api/1/energyProduced
producers:
  growatt: growatt