cassandra:
  port: 9042
  keyspace: "openklaster"

sourcemeasurement:
  address: "openklaster.cassandraservice.sourcemeasurement"
  table: "sourcemeasurement"
  idtype: "inverterId"

loadmeasurement:
  address: "openklaster.cassandraservice.loadmeasurement"
  table: "loadmeasurement"
  idtype: "receiverId"

energypredictions:
  address: "openklaster.cassandraservice.energypredictions"
  table: "energypredictions"
  idtype: "installationId"

weatherconditions:
  address: "openklaster.cassandraservice.weatherconditions"
  table: "weatherconditions"
  idtype: "installationId"