spring:
  profiles:
    active: EXTRACTOR_OFF
  data:
    cassandra:
      keyspace-name: openklaster
      local-datacenter: datacenter1
      port: 9042
      contact-points: localhost
      schemaAction: CREATE_IF_NOT_EXISTS
    mongodb:
      database: DEFAULT_DB
      port: 27017
      host: localhost
  mvc:
    format:
      date-time: yyyy-MM-dd HH:mm:ss
      date: yyyy-MM-dd
      time: HH:mm:ss
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

server:
  port: 8082
  servlet:
    context-path: /api/1
openklaster:
  power-energy:
    enabled: false
    installation-id: "-"
  files:
    base-path: ../file-repository/data
  mqtt:
    enabled: false
    topic: "-"
    address: "-"
    port: 1883
    cipher-key: "-"
    installation-id: "-"