version: '3'
services:
  openklaster-backend:
    build:
      context: OpenKlasterApplication
      dockerfile: docker/Dockerfile
    environment:
      - TZ=Poland
    ports:
      - "8082:8082"
    volumes:
      - ./file-repository:/file-repository
    restart: always
  openklaster-webpage:
    build:
      context: .
      dockerfile: OpenKlasterWeb/Dockerfile
      network: host
    environment:
      - API_URL=http://localhost/
    ports:
      - "80:80"
    restart: always
  mongo-db:
    image: 'mongo'
    environment:
      - MONGO_INITDB_DATABASE=DEFAULT_DB
    volumes:
      - ./mongo-volume:/data/db
    expose:
      - '27017-27019'
    ports:
      - "27017:27017"
    restart: always
  cassandra-db:
      image: cassandra:latest
      expose:
        - "9042"
      ports:
        - "9042:9042"
      volumes:
        - ./data/cassandra:/var/lib/cassandra
      restart: always
  grav:
    build:
      context: grav
      network: host
    volumes:
      - ./grav/grav-data/:/var/www/html/user
    restart: always
