http:
  port: 8082
  endpoint:
    route:
      user: "/user"
      load: "/load"
      source: "/source"
      inverter: "/inverter"
      installation: "/installation"
      energySourceCalculator: "/energySourceCalculator"

core:
  route:
    user: "openKlaster.core.user"
    load: "openKlaster.core.load"
    source: "openKlaster.core.source"
    inverter: "openKlaster.core.inverter"
    installation: "openKlaster.core.installation"
    energySourceCalculator: "openKlaster.core.energySourceCalculator"



energy:
  endpoint:
    route:
      main: "/energy"
      production: "/production"
      consumption: "/consumption"
    consumes: "application/json"

power:
  endpoint:
    route:
      main: "/power"
      production: "/production"
      consumption: "/consumption"
    consumes: "application/json"

cassandra:
  port: 8191
  host: "localhost"
  consumes: "application/json"
  route:
    load: "/loadmeasurement"
    source: "/sourcemeasurement"

eventBus:
  timeout: 15000

