http:
  port: 8082
  endpoint:
    route:
      login: "/api/1/user/login"
      user: "/api/1/user"
      token: "/api/1/token"
      installation: "/api/1/installations"
      powerconsumption: "/api/1/powerConsumption"
      powerproduction: "/api/1/powerConsumption"
      energyconsumed: "/api/1/energyConsumed"
      energyproduced: "/api/1/energyProduced"

core:
  route:
    login: "openklaster.core.login"
    user: "openklaster.core.user"
    token: "openklaster.core.token"
    installation: "openklaster.core.installation"
    powerconsumption: "openklaster.core.powerconsumption"
    powerproduction: "openklaster.core.powerproduction"
    energyconsumed: "openklaster.core.energyconsumed"
    energyproduced: "openklaster.core.energyproduced"

eventBus:
  timeout: 15000

