security:
  tokens:
    charsPerType: 4 #how many chars included in generated token per type /number/upper/lower/special
    sessionTokenLifetime: 30 #for how many minutes session token is valid
eventbus:
  in:
    userManagement:
      address: "openklaster.core.user"
    installations:
      address: "openklaster.core.installation"
    sourceMeasurements:
      address: "openklaster.core.production"
    loadMeasurements:
      address: "openklaster.core.consumption"
  out:
    mongo:
      users:
        address: "openklaster.mongo.user"
      installation:
        address: "openklaster.mongo.installation"
    cassandra:
      loadmeasurement:
        address: "openklaster.cassandraservice.loadmeasurement"
      sourcemeasurement:
        address: "openklaster.cassandraservice.sourcemeasurement"

