database:
  mongo:
    host: "mongo-db"
    port: 27017
  mongoAuth:

calculator:
  mongo:
    collectionName: "calculators"
  bus:
    address: "openklaster.mongo.calculators"

installation:
  mongo:
    collectionName: "installations"
  bus:
    address: "openklaster.mongo.installation"

user:
  mongo:
    collectionName: "userz"
  bus:
    address: "openklaster.mongo.user"
