http:
  port: 8082

energy:
  endpoint:
    route:
      main: "/energy"
      production: "/production"
      consumption: "/consumption"
    consumes: "application/json"

power:
  endpoint:
    route:
      main: "/power"
      production: "/production"
      consumption: "/consumption"
    consumes: "application/json"

cassandra:
  port: 8191
  host: "localhost"
  consumes: "application/json"
  route:
    load: "/loadmeasurement"
    source: "/sourcemeasurement"